export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const CLEAR_ALL_CART_ITEM = 'CLEAR_ALL_CART_ITEM';

export const ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM';
export const DELETE_WISHLIST_ITEM = 'DELETE_WISHLIST_ITEM';